app = "omely-node-backend"
primary_region = "cdg"

[build]

[env]
  PORT = "3000"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  # Paramètres explicites pour éviter l'arrêt automatique
  concurrency = { type = "requests", soft_limit = 1000, hard_limit = 2000 }

[[http_service.checks]]
  grace_period = "20s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[scaling]
  min_machines_running = 1
  max_machines_running = 3

[machine]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[processes]]
  name = "app"
  command = "npm start"
