[build]
  # Force static site - NO build process
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  # Force Node.js and disable Python
  NODE_VERSION = "18"
  NPM_FLAGS = "--ignore-scripts --no-optional --no-audit --no-fund"
  # Explicitly disable Python
  PYTHON_VERSION = ""
  # Disable Python detection completely
  PYTHON_ENABLED = "false"

# Handle all routes (SPA-like behavior)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=0, must-revalidate"

# Explicitly ignore Python files
[build.processing]
  skip_processing = false

# Completely disable Python
[build.environment]
  PYTHON_ENABLED = "false"
  PYTHON_VERSION = ""
  NODE_VERSION = "18"
