[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"
  PYTHON_ENABLED = "false"
  NPM_FLAGS = "--ignore-scripts --no-optional --no-audit --no-fund"
  SKIP_DEPENDENCY_CACHE = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
