# fly.toml app configuration file generated for omely-backend on 2024-12-14T15:12:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "omely-backend"
primary_region = "cdg"

[build]

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 2048

[mounts]
  source = "omely_data"
  destination = "/tmp"

[processes]
  app = "python -m uvicorn main:app --host 0.0.0.0 --port 8000"


