services:
  - type: web
    name: omely-backend
    runtime: node
    buildCommand: npm ci --only=production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: OPENAI_API_KEY
        sync: false # À définir manuellement dans Render
